on:
  push:
    branches:
      - main
      - staging
      - production

name: Tag build with appropriate version on PR merge

jobs:
  tag-dev:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Create tag for dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tag main
        run: |
          VERSION=`git describe --tags --abbrev=0 | awk -F. -v OFS=. '{print $NF+1}'`
          git config --global user.email "auto-tagger@learningGHActions.com"
          git config --global user.name "Auto Tagger"
          git tag -a dev-${VERSION} -m "tag check"
          git push origin dev-${VERSION}


